/** Raw task rows: cefrLevel is a Level.code string; category maps to scenarioType in seed. */
export const practiceTasks = [
  // Career (8)
  {
    title: "Introduce Yourself",
    description: "Give a brief self-introduction in English",
    instructions: "Introduce yourself in 60-90 seconds. Include: your name, what you do, where you're from, and one interesting fact about you.",
    cefrLevel: "A2",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 90,
  },
  {
    title: "Describe Your Current Role",
    description: "Explain your job and responsibilities",
    instructions: "Describe your current role in 2-3 minutes. Include: job title, main responsibilities, team size, and what you enjoy most.",
    cefrLevel: "B1",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 180,
  },
  {
    title: "Explain Your Work Experience",
    description: "Walk through your career timeline",
    instructions: "Summarize your work experience in chronological order. Mention: previous companies, roles, key achievements, and why you moved between jobs.",
    cefrLevel: "B1",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 180,
  },
  {
    title: "Simulate Interview Answer",
    description: "Answer a common interview question",
    instructions: "Answer: 'Tell me about yourself' or 'What is your greatest weakness?'. Speak for 2-3 minutes as if in a real interview.",
    cefrLevel: "B1",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 180,
  },
  {
    title: "Talk About Career Goals",
    description: "Discuss your future professional aspirations",
    instructions: "Explain where you see yourself in 3-5 years. Include: career milestones you want to achieve and how you're planning to get there.",
    cefrLevel: "B2",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 180,
  },
  {
    title: "Describe a Challenge at Work",
    description: "Explain a professional problem and solution",
    instructions: "Describe a challenging situation at work. Include: the context, the problem, your approach, and the outcome.",
    cefrLevel: "B1",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 180,
  },
  {
    title: "Explain a Promotion",
    description: "Describe how you achieved a promotion",
    instructions: "Share the story of how you got promoted. Include: what you did differently, the skills you developed, and what you learned.",
    cefrLevel: "B2",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 180,
  },
  {
    title: "Discuss Team Leadership",
    description: "Talk about managing and leading teams",
    instructions: "Describe your experience leading teams. Include: team size, leadership style, challenges faced, and how you motivated your team.",
    cefrLevel: "B2",
    skillType: "speaking",
    category: "career",
    estimatedDurationSec: 180,
  },

  // Product/Tech (8)
  {
    title: "Explain a Product Feature",
    description: "Describe a feature you worked on",
    instructions: "Explain a product feature in 2-3 minutes. Include: what it does, who it's for, why it matters, and how it works.",
    cefrLevel: "B1",
    skillType: "speaking",
    category: "product",
    estimatedDurationSec: 180,
  },
  {
    title: "Describe a Technical Decision",
    description: "Explain a trade-off you made",
    instructions: "Describe a technical decision you made. Include: the options you considered, trade-offs, your choice, and the outcome.",
    cefrLevel: "B2",
    skillType: "speaking",
    category: "product",
    estimatedDurationSec: 180,
  },
  {
    title: "Present a Project Overview",
    description: "Summarize a project you led",
    instructions: "Present an overview of a project in 3 minutes. Include: problem, solution, team, timeline, challenges, and results.",
    cefrLevel: "B2",
    skillType: "speaking",
    category: "product",
    estimatedDurationSec: 180,
  },
  {
    title: "Explain a Bug Fix",
    description: "Describe debugging a complex issue",
    instructions: "Walk through how you fixed a bug. Include: how you reproduced it, the root cause, your approach, and what you learned.",
    cefrLevel: "B1",
    skillType: "speaking",
    category: "product",
    estimatedDurationSec: 180,
  },
  {
    title: "Discuss Architecture Decisions",
    description: "Explain your system design choices",
    instructions: "Discuss architecture decisions for a system. Include: requirements, alternatives considered, final choice, and pros/cons.",
    cefrLevel: "C1",
    skillType: "speaking",
    category: "product",
    estimatedDurationSec: 240,
  },
  {
    title: "Describe a Tech Stack",
    description: "Explain the technologies you use",
    instructions: "Describe your current tech stack. Include: languages, frameworks, tools, why you chose each, and what you like/dislike.",
    cefrLevel: "B1",
    skillType: "speaking",
    category: "product",
    estimatedDurationSec: 180,
  },
  {
    title: "Talk About Code Review",
    description: "Discuss your code review process",
    instructions: "Explain how you conduct code reviews. Include: what you look for, how you give feedback, and how you handle disagreements.",
    cefrLevel: "B2",
    skillType: "speaking",
    category: "product",
    estimatedDurationSec: 180,
  },
  {
    title: "Explain a Technical Concept",
    description: "Teach a technical topic",
    instructions: "Explain a technical concept as if teaching someone. Pick a concept you're familiar with and explain it clearly in 2-3 minutes.",
    cefrLevel: "B2",
    skillType: "fluency",
    category: "product",
    estimatedDurationSec: 180,
  },

  // General Fluency (8)
  {
    title: "Give Your Opinion",
    description: "Express your viewpoint on a topic",
    instructions: "Give your opinion on: 'Is work-life balance achievable in tech?'. Speak for 90 seconds, giving reasons and examples.",
    cefrLevel: "B1",
    skillType: "fluency",
    category: "fluency",
    estimatedDurationSec: 90,
  },
  {
    title: "Tell a Story",
    description: "Narrate a personal experience",
    instructions: "Tell a story about something memorable that happened to you. Include: setting, characters, what happened, and why it matters.",
    cefrLevel: "B1",
    skillType: "fluency",
    category: "fluency",
    estimatedDurationSec: 180,
  },
  {
    title: "Summarize a Video",
    description: "Recap something you watched",
    instructions: "Summarize a video or presentation you watched recently. Include: main points, key insights, and your reaction.",
    cefrLevel: "B1",
    skillType: "fluency",
    category: "fluency",
    estimatedDurationSec: 180,
  },
  {
    title: "Compare Two Things",
    description: "Analyze two options",
    instructions: "Compare: 'Remote work vs Office work'. Discuss pros and cons of each, and give your preference with reasoning.",
    cefrLevel: "B1",
    skillType: "fluency",
    category: "fluency",
    estimatedDurationSec: 180,
  },
  {
    title: "Describe Your Day",
    description: "Narrate your daily routine",
    instructions: "Describe your typical day in 2 minutes. Include: morning routine, work/school activities, evening routine, and what you enjoy most.",
    cefrLevel: "A2",
    skillType: "speaking",
    category: "fluency",
    estimatedDurationSec: 120,
  },
  {
    title: "Talk About Hobbies",
    description: "Share your interests",
    instructions: "Talk about your hobbies and interests. Include: what you do, how often, why you enjoy it, and who you do it with.",
    cefrLevel: "A2",
    skillType: "speaking",
    category: "fluency",
    estimatedDurationSec: 120,
  },
  {
    title: "Explain a Process",
    description: "Describe how something works",
    instructions: "Explain a process you know well (cooking, coding, driving, etc). Walk through the steps in logical order.",
    cefrLevel: "B1",
    skillType: "fluency",
    category: "fluency",
    estimatedDurationSec: 180,
  },
  {
    title: "Discuss Current Events",
    description: "Share thoughts on news",
    instructions: "Discuss a recent news story you found interesting. Include: what happened, your opinion, and why it matters.",
    cefrLevel: "B2",
    skillType: "fluency",
    category: "fluency",
    estimatedDurationSec: 180,
  },

  // Content Reflection (6)
  {
    title: "Summarize What You Learned",
    description: "Recap educational content",
    instructions: "Summarize something you learned from a video, article, or course. Include: main takeaways and how you can apply it.",
    cefrLevel: "B1",
    skillType: "fluency",
    category: "reflection",
    estimatedDurationSec: 180,
  },
  {
    title: "React to Content",
    description: "Give your reaction to media",
    instructions: "React to a piece of content you consumed. Include: what stood out, what you agreed/disagreed with, and why.",
    cefrLevel: "B2",
    skillType: "fluency",
    category: "reflection",
    estimatedDurationSec: 180,
  },
  {
    title: "Connect to Experience",
    description: "Link content to your life",
    instructions: "Connect what you learned to a personal experience. Explain: the connection, similarities, differences, and insights gained.",
    cefrLevel: "B2",
    skillType: "fluency",
    category: "reflection",
    estimatedDurationSec: 180,
  },
  {
    title: "Teach What You Learned",
    description: "Explain to teach others",
    instructions: "Explain a concept as if teaching someone who doesn't know anything about it. Be clear, patient, and use examples.",
    cefrLevel: "B2",
    skillType: "fluency",
    category: "reflection",
    estimatedDurationSec: 180,
  },
  {
    title: "Apply Knowledge",
    description: "Practical application of learning",
    instructions: "Explain how you would apply what you learned to a real situation. Include: specific steps and expected outcomes.",
    cefrLevel: "B2",
    skillType: "fluency",
    category: "reflection",
    estimatedDurationSec: 180,
  },
  {
    title: "Identify Gaps",
    description: "Self-assessment of knowledge",
    instructions: "Identify what you don't fully understand yet. Include: topics you need to learn more about and how you plan to fill the gaps.",
    cefrLevel: "B1",
    skillType: "fluency",
    category: "reflection",
    estimatedDurationSec: 120,
  },
]